"""
Sedes y emisión en España (DAZN / TVE La 1) — Copa Mundial FIFA 2026.
Fuentes: calendario FIFA + calendario TV España (RTVC / DAZN).
"""

# row → {city, country, tv}
# tv: "dazn" | "tve" | "both"
FIXTURE_BY_ROW = {
    # ── Fase de grupos — jornada 1 ──
    6:  {"city": "Ciudad de México", "country": "México", "tv": "both"},
    7:  {"city": "Guadalajara",      "country": "México", "tv": "dazn"},
    8:  {"city": "Toronto",          "country": "Canadá", "tv": "both"},
    9:  {"city": "San Francisco",    "country": "EE.UU.", "tv": "dazn"},
    10: {"city": "Nueva York",       "country": "EE.UU.", "tv": "dazn"},
    11: {"city": "Boston",           "country": "EE.UU.", "tv": "dazn"},
    12: {"city": "Los Ángeles",      "country": "EE.UU.", "tv": "dazn"},
    13: {"city": "Vancouver",        "country": "Canadá", "tv": "dazn"},
    14: {"city": "Houston",          "country": "EE.UU.", "tv": "both"},
    15: {"city": "Filadelfia",       "country": "EE.UU.", "tv": "dazn"},
    16: {"city": "Dallas",           "country": "EE.UU.", "tv": "dazn"},
    17: {"city": "Monterrey",        "country": "México", "tv": "dazn"},
    18: {"city": "Seattle",          "country": "EE.UU.", "tv": "dazn"},
    19: {"city": "Los Ángeles",      "country": "EE.UU.", "tv": "dazn"},
    20: {"city": "Atlanta",          "country": "EE.UU.", "tv": "both"},
    21: {"city": "Miami",            "country": "EE.UU.", "tv": "dazn"},
    22: {"city": "Nueva York",       "country": "EE.UU.", "tv": "both"},
    23: {"city": "Boston",           "country": "EE.UU.", "tv": "dazn"},
    24: {"city": "Kansas City",      "country": "EE.UU.", "tv": "dazn"},
    25: {"city": "San Francisco",    "country": "EE.UU.", "tv": "dazn"},
    26: {"city": "Houston",          "country": "EE.UU.", "tv": "dazn"},
    27: {"city": "Ciudad de México", "country": "México", "tv": "dazn"},
    28: {"city": "Dallas",           "country": "EE.UU.", "tv": "both"},
    29: {"city": "Toronto",          "country": "Canadá", "tv": "dazn"},
    # ── jornada 2 ──
    30: {"city": "Atlanta",          "country": "EE.UU.", "tv": "dazn"},
    31: {"city": "Guadalajara",      "country": "México", "tv": "dazn"},
    32: {"city": "Los Ángeles",      "country": "EE.UU.", "tv": "both"},
    33: {"city": "Vancouver",        "country": "Canadá", "tv": "dazn"},
    34: {"city": "Boston",           "country": "EE.UU.", "tv": "dazn"},
    35: {"city": "Filadelfia",       "country": "EE.UU.", "tv": "dazn"},
    36: {"city": "Seattle",          "country": "EE.UU.", "tv": "both"},
    37: {"city": "San Francisco",    "country": "EE.UU.", "tv": "dazn"},
    38: {"city": "Toronto",          "country": "Canadá", "tv": "dazn"},
    39: {"city": "Kansas City",      "country": "EE.UU.", "tv": "dazn"},
    40: {"city": "Houston",          "country": "EE.UU.", "tv": "both"},
    41: {"city": "Monterrey",        "country": "México", "tv": "dazn"},
    42: {"city": "Los Ángeles",      "country": "EE.UU.", "tv": "dazn"},
    43: {"city": "Vancouver",        "country": "Canadá", "tv": "dazn"},
    44: {"city": "Atlanta",          "country": "EE.UU.", "tv": "both"},
    45: {"city": "Miami",            "country": "EE.UU.", "tv": "dazn"},
    46: {"city": "Filadelfia",       "country": "EE.UU.", "tv": "dazn"},
    47: {"city": "Nueva York",       "country": "EE.UU.", "tv": "dazn"},
    48: {"city": "Dallas",           "country": "EE.UU.", "tv": "both"},
    49: {"city": "San Francisco",    "country": "EE.UU.", "tv": "dazn"},
    50: {"city": "Houston",          "country": "EE.UU.", "tv": "dazn"},
    51: {"city": "Guadalajara",      "country": "México", "tv": "dazn"},
    52: {"city": "Boston",           "country": "EE.UU.", "tv": "both"},
    53: {"city": "Toronto",          "country": "Canadá", "tv": "dazn"},
    # ── jornada 3 ──
    54: {"city": "Ciudad de México", "country": "México", "tv": "dazn"},
    55: {"city": "Monterrey",        "country": "México", "tv": "dazn"},
    56: {"city": "Vancouver",        "country": "Canadá", "tv": "dazn"},
    57: {"city": "Seattle",          "country": "EE.UU.", "tv": "dazn"},
    58: {"city": "Miami",            "country": "EE.UU.", "tv": "dazn"},
    59: {"city": "Atlanta",          "country": "EE.UU.", "tv": "dazn"},
    60: {"city": "Los Ángeles",      "country": "EE.UU.", "tv": "dazn"},
    61: {"city": "San Francisco",    "country": "EE.UU.", "tv": "dazn"},
    62: {"city": "Filadelfia",       "country": "EE.UU.", "tv": "dazn"},
    63: {"city": "Nueva York",       "country": "EE.UU.", "tv": "both"},
    64: {"city": "Dallas",           "country": "EE.UU.", "tv": "dazn"},
    65: {"city": "Kansas City",      "country": "EE.UU.", "tv": "dazn"},
    66: {"city": "Seattle",          "country": "EE.UU.", "tv": "dazn"},
    67: {"city": "Vancouver",        "country": "Canadá", "tv": "dazn"},
    68: {"city": "Houston",          "country": "EE.UU.", "tv": "dazn"},
    69: {"city": "Guadalajara",      "country": "México", "tv": "both"},
    70: {"city": "Boston",           "country": "EE.UU.", "tv": "dazn"},
    71: {"city": "Toronto",          "country": "Canadá", "tv": "dazn"},
    72: {"city": "Kansas City",      "country": "EE.UU.", "tv": "dazn"},
    73: {"city": "Dallas",           "country": "EE.UU.", "tv": "dazn"},
    74: {"city": "Miami",            "country": "EE.UU.", "tv": "both"},
    75: {"city": "Atlanta",          "country": "EE.UU.", "tv": "dazn"},
    76: {"city": "Nueva York",       "country": "EE.UU.", "tv": "dazn"},
    77: {"city": "Filadelfia",       "country": "EE.UU.", "tv": "dazn"},
    # ── Dieciseisavos ──
    164: {"city": "Los Ángeles",      "country": "EE.UU.", "tv": "dazn"},
    165: {"city": "Houston",          "country": "EE.UU.", "tv": "dazn"},
    166: {"city": "Boston",           "country": "EE.UU.", "tv": "dazn"},
    167: {"city": "Monterrey",        "country": "México", "tv": "dazn"},
    168: {"city": "Dallas",           "country": "EE.UU.", "tv": "dazn"},
    169: {"city": "Nueva York",       "country": "EE.UU.", "tv": "dazn"},
    170: {"city": "Ciudad de México", "country": "México", "tv": "both"},
    171: {"city": "Atlanta",          "country": "EE.UU.", "tv": "dazn"},
    172: {"city": "Seattle",          "country": "EE.UU.", "tv": "dazn"},
    173: {"city": "San Francisco",    "country": "EE.UU.", "tv": "dazn"},
    174: {"city": "Los Ángeles",      "country": "EE.UU.", "tv": "dazn"},
    175: {"city": "Toronto",          "country": "Canadá", "tv": "dazn"},
    176: {"city": "Vancouver",        "country": "Canadá", "tv": "dazn"},
    177: {"city": "Dallas",           "country": "EE.UU.", "tv": "dazn"},
    178: {"city": "Miami",            "country": "EE.UU.", "tv": "dazn"},
    179: {"city": "Kansas City",      "country": "EE.UU.", "tv": "dazn"},
    # ── Octavos ──
    200: {"city": "Filadelfia",       "country": "EE.UU.", "tv": "dazn"},
    201: {"city": "Houston",          "country": "EE.UU.", "tv": "dazn"},
    202: {"city": "Nueva York",       "country": "EE.UU.", "tv": "dazn"},
    203: {"city": "Ciudad de México", "country": "México", "tv": "both"},
    204: {"city": "Dallas",           "country": "EE.UU.", "tv": "dazn"},
    205: {"city": "Seattle",          "country": "EE.UU.", "tv": "dazn"},
    206: {"city": "Atlanta",          "country": "EE.UU.", "tv": "dazn"},
    207: {"city": "Vancouver",        "country": "Canadá", "tv": "dazn"},
    # ── Cuartos ──
    220: {"city": "Boston",           "country": "EE.UU.", "tv": "dazn"},
    221: {"city": "Los Ángeles",      "country": "EE.UU.", "tv": "both"},
    222: {"city": "Miami",            "country": "EE.UU.", "tv": "dazn"},
    223: {"city": "Kansas City",      "country": "EE.UU.", "tv": "dazn"},
    # ── Semis ──
    232: {"city": "Dallas",           "country": "EE.UU.", "tv": "both"},
    233: {"city": "Atlanta",          "country": "EE.UU.", "tv": "both"},
    # ── 3º puesto y Final ──
    244: {"city": "Miami",            "country": "EE.UU.", "tv": "both"},
    247: {"city": "Nueva York",       "country": "EE.UU.", "tv": "both"},
}

TV_LABELS = {
    "dazn": "DAZN",
    "tve":  "TVE La 1",
    "both": "DAZN + TVE La 1",
}


def lookup_fixture(row: int) -> dict:
    return FIXTURE_BY_ROW.get(row, {})
